main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('someapp.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns = [
                      path('__debug__/', include('debug_toolbar.urls')),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

someapp/urls.py
from django.urls import path, include
from . import views
from interactions.views import ActionDetailView, ActionCreateView, ActionUpdate, ActionDelete, AddLikeView, \
    CreateKeyword, FilterKeywordView

urlpatterns = [
    path('company-list/', include([
        path('', views.CompanyListView.as_view(), name='companies'),
        path('new-company/', views.CompanyCreate.as_view(), name='new-company'),
        path('<slug:slug>/', include([
            path('', views.CompanyDetailView.as_view(), name='company-details'),
            path('update/', views.CompanyUpdate.as_view(), name='update-company'),
            path('delete/', views.CompanyDelete.as_view(), name='delete-company'),
            path('new-project/', views.ProjectCreate.as_view(), name='new-project'),
        ])),
        path('<slug:company_slug>/<slug:project_slug>/', include([
            path('', views.ProjectDetailView.as_view(), name='project-details'),
            path('update/', views.ProjectUpdate.as_view(), name='update-project'),
            path('delete/', views.ProjectDelete.as_view(), name='delete-project'),
            path('new-action/', include([
                path('', ActionCreateView.as_view(), name='new-action'),
                path('new-keyword/', CreateKeyword.as_view(), name='create-keyword'),
            ])),
            path('<int:pk>/', ActionDetailView.as_view(), name='interaction-details'),
            path('<int:pk>/update/', ActionUpdate.as_view(), name='update-action'),
            path('<int:pk>/delete/', ActionDelete.as_view(), name='delete-action'),
        ])),

    ])),
    path('project-list/', include([
        path('', views.ProjectListView.as_view(), name='projects'),
    ])),
    path('all-projects-keyword/', FilterKeywordView.as_view(), name='filter-keyword'),
    path('add-like/', AddLikeView.as_view(), name='add_like'),
]

interactions/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse_lazy
from main import settings
from main.constants import APPEALS
from someapp.models import Project, Company


class Interaction(models.Model):
    """Model representing a interactions between company and manager"""
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    appeals = models.CharField(max_length=2, choices=APPEALS.choices, default=APPEALS.REQUEST)
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = RichTextField(config_name='comment_ckeditor')
    keyword = models.ManyToManyField('Keyword', related_name='keyword', blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_date',)
        verbose_name = 'interaction'
        verbose_name_plural = 'interactions'

    def __str__(self) -> str:
        """String for representing a interaction object."""
        return self.get_appeals()

    def get_appeals(self) -> str:
        """Method to get a value of appeals"""
        return f'{APPEALS(self.appeals).label}'


class Keyword(models.Model):
    """Model representing a keyword"""
    title = models.CharField(max_length=255, unique=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_date',)
        verbose_name = 'keyword'
        verbose_name_plural = 'keywords'

    def __str__(self) -> str:
        """String for representing a keyword object."""
        return f'{self.title}'


class Like(models.Model):
    """Model representing a Like"""
    who = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    action = models.ForeignKey(Interaction, on_delete=models.CASCADE)
    like = models.ForeignKey("Rating", on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_date',)
        verbose_name = 'like'
        verbose_name_plural = 'likes'

    def __str__(self) -> str:
        """String for representing the CommentLike object."""
        return f'{self.action} - {self.who}'


class Rating(models.Model):
    """Model representing a Rating"""
    value = models.SmallIntegerField(default=0)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-value',)
        verbose_name = 'rating'
        verbose_name_plural = 'rating'

    def __str__(self) -> str:
        """String for representing a Rating object."""
        return f'{self.value}'

someapp/models.py
from typing import Any, List
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
from slugify import slugify
from main import settings
import datetime


class Company(models.Model):
    """Model representing a company"""
    title = models.CharField(max_length=250, help_text="Enter a name of company", unique=True)
    slug = models.SlugField()
    contact_person = models.CharField(max_length=250, help_text="Enter a name of the head of the company")
    description = RichTextField()
    address = models.CharField(max_length=255, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('title', 'created_date',)
        verbose_name = 'company'
        verbose_name_plural = 'companies'

    def __str__(self) -> str:
        """String for representing the Client object."""
        return f'{self.title}'

    def save(self, *args: Any, **kwargs: Any) -> None:
        """Filling in the slug field"""
        if not self.slug:
            self.slug = slugify(self.title)
        super(Company, self).save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        """Canonical URL for an object"""
        return reverse('company-details', kwargs={'slug': self.slug})


class Phone(models.Model):
    """Model representing a phone number"""
    valid_re = RegexValidator(regex=r"\d{3}-\d{7}",
                              message="Phone number must be entered in the format: '000-0000000'. Up to 11 digits "
                                      "allowed.")
    phone_number = models.CharField(validators=[valid_re], max_length=11, null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('company',)
        verbose_name = 'phone number'
        verbose_name_plural = 'phone numbers'

    def __str__(self) -> str:
        """String for representing a phone number object."""
        return f'{self.phone_number}'


class Email(models.Model):
    """Model representing a e-mail address"""
    email_address = models.EmailField(max_length=250, null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('company',)
        verbose_name = 'email address'
        verbose_name_plural = 'email addresses'

    def __str__(self) -> str:
        """String for representing a email address object."""
        return f'{self.email_address}'


class Project(models.Model):
    """Model representing a project"""
    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField()
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, default='', null=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, related_name="responsible",
                                default='', null=True)
    description = RichTextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    begin = models.DateField(null=True, blank=True)
    end = models.DateField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    today_date = datetime.date.today()

    class Meta:
        ordering = ('title',)
        verbose_name = 'project'
        verbose_name_plural = 'projects'

    def save(self, *args: Any, **kwargs: Any) -> None:
        """Filling in the slug field"""
        if not self.slug:
            self.slug = slugify(self.title)
        super(Project, self).save(*args, **kwargs)

    def __str__(self) -> str:
        """String for representing a project object."""
        return f'{self.title}'

    def get_absolute_url(self) -> str:
        """Canonical URL for an object"""
        return reverse('project-details',
                       kwargs={'company_slug': slugify(str(self.company)),
                               'project_slug': self.slug})

    @property
    def days_to(self) -> List[str]:
        """Сalculation of the project status for today"""
        date_diff_start = (self.begin - self.today_date).days
        date_diff_end = (self.end - self.today_date).days
        if (date_diff_start >= 0) and (date_diff_start < 4):
            return [f'left {date_diff_start} day', 'text-secondary']
        elif date_diff_start >= 4:
            return [f'left {date_diff_start} days', 'text-secondary']
        elif (date_diff_start < 0) and (date_diff_end >= 0):
            return ['In Progress', 'text-info']
        elif (date_diff_start < 0) and (date_diff_end < 0):
            return ['Completed', 'text-success']

someapp/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Company, Email, Phone, Project


class CompanyForm(forms.ModelForm):
    """Form for create or update company objects"""
    class Meta:
        model = Company
        fields = ('title', 'contact_person', 'description', 'address',)


PhoneInlineFormSet = inlineformset_factory(
    Company, Phone, fields=('phone_number',), extra=1, max_num=5, can_delete=True)
EmailInlineFormSet = inlineformset_factory(
    Company, Email, fields=('email_address',), extra=1, max_num=5, can_delete=True)


class DateInput(forms.DateInput):
    """Assignment to a field of type date
    Attributes:
        input_type (str): specifies the type of the assigned field
    """
    input_type = 'date'


class ProjectForm(forms.ModelForm):
    """Form for create a new project objects"""
    class Meta:
        model = Project
        fields = ('title', 'company', 'description', 'creator', 'begin', 'end', 'price',)
        widgets = {
            'begin': DateInput(),
            'end': DateInput(),
        }


class ProjectUpdateForm(forms.ModelForm):
    """Form for update the project objects"""
    class Meta:
        model = Project
        exclude = ('company', 'creator', 'today_date', )
        widgets = {
            'begin': DateInput(),
            'end': DateInput(),
        }

someapp/templates/someapp/companies.html
{% extends 'base.html' %}

{% load static %}

{% load templatetags %}

{% block addjs %}
<script src="{% static 'js/sorting.js' %}"></script>
{% endblock %}

{% block title %}
    Company List
{% endblock %}

{% block content %}

    <noscript class="d-block text-center bg-warning text-light py-3">
        This page requires Javascript to work correctly.
    </noscript>

    {% if messages %}
        {% include "message.html" %}
    {% endif %}

    <main class="container">
        <div class="row">
            {% if companies %}
            <div class="col-9 mx-auto col-md-12 col-lg-12">
                <h1 class="my-5 text-center">Company List</h1>
                {% if perms.someapp.add_company %}
                <a href="{% url 'new-company' %}"> + Add</a>
                {% endif %}

                <form method="get" class="text-right">
                    <select name="sorting" id="sorting" class="text-secondary p-2 ml-2">
                    {% for key, value in filterset.field.choices %}
                    <option value="{{ key }}">{{ value }}</option>
                    {% endfor %}
                    </select>
                </form>

                <script>
                        $('#sorting').on('change', function () {$(this.form).submit();});

                    let path = '{{ request.get_full_path|cut:request.path }}'.slice(1,);
                        reqObj = getDict(path);
                </script>

                {% for company in companies %}
                <div class="card my-2">
                    <details>
                        <summary class="card-header position-relative">{{ company.title }}
                            <span class="text-muted">(The contact person: {{ company.contact_person }})</span>
                            {% if perms.someapp.change_company %}
                            <a class="ml-3" href="{% url 'update-company' company.slug %}">
                                <span class="material-icons fs-1">edit</span>
                            </a>
                            {% endif %}
                            {% if perms.someapp.delete_company %}
                            <a class="m-0 position-absolute delete-btn-company"
                               href="{% url 'delete-company' company.slug %}">
                                <span class="material-icons fs-1">close</span>
                            </a>
                            {% endif %}
                            <cite class="text-warning float-right" style="font-size: 10pt;">
                                last changed: {{ company.updated_date|date:"d.m.Y" }}
                                in {{ company.updated_date|time:"H:i" }}</cite></summary>
                        <div class="card-body">
                            <h4 class="card-title"><em>The contact person: {{ company.contact_person }}</em></h4>
                            <p class="card-text">{{ company.description|safe }}</p>
                            <br>
                            <a href="{{ company.get_absolute_url }}" class="btn btn-outline-info px-5 float-right">
                                Details
                            </a>
                            <div class="clearfix">
                        </div>
                    </details>
                </div>
                {% endfor %}
            </div>

            <nav class="container mt-5">
                <ul class="pagination">
                    {% if is_paginated %}
                        {% include "pagination.html" %}
                    {% endif %}
                </ul>
            </nav>
            {% else %}
            <h3 class="text-secondary get-center">
                There are no companies available
                {% if perms.someapp.add_company %}
                <small class="d-block text-center mt-3">
                    <a href="{% url 'new-company' %}"> + add a new company</a>
                </small>
                {% endif %}
            </h3>
            {% endif %}

        </div>
    </main>

{% endblock %}

someapp/templates/someapp/company-details.html
{% extends 'base.html' %}

{% load static %}

{% load templatetags %}

{% block addjs %}
<script src="{% static 'js/sorting.js' %}"></script>
{% endblock %}

{% block title %}
    {{ company.title }}
{% endblock %}

{% block content %}

    <main class="container">
        <div class="row">
            <div class="col-9 mx-auto col-md-12 col-lg-12">
                <h1 class="my-5">{{ company.title }}
                    {% if perms.someapp.change_company %}
                    <a class="ml-5" href="{% url 'update-company' company.slug %}">
                        <span class="material-icons">edit</span>
                    </a>
                    {% endif %}
                    {% if perms.someapp.delete_company %}
                    <a class="ml-5" href="{% url 'delete-company' company.slug %}">
                        <span class="material-icons">delete</span>
                    </a>
                    {% endif %}
                </h1>
                <small class="card-title mb-4 font-italic">The contact person: {{ company.contact_person }}</small>
                <img src="" alt="">
                <p class="card-text">{{ company.description|safe }}</p>
                <p class="text-uppercase my-5 text-underline">Contact Details:</p>
                <dl class="row ml-5">
                    <dt class="col-sm-3 mb-3">Address:</dt>
                        <dd class="col-sm-9">{{ company.address }}</dd>
                    <dt class="col-sm-3 mb-3">Phone numbers:</dt>
                        <dd class="col-sm-9">
                            <ul class="list-unstyled">
                            {% for number in company.phone_set.all %}
                                {% if number.company_id == company.id %}
                                <li>+38-{{ number }}</li>
                                {% endif %}
                            {% endfor %}
                            </ul>
                        </dd>
                    <dt class="col-sm-3 mb-3">Email addresses:</dt>
                        <dd class="col-sm-9">
                            <ul class="list-unstyled">
                            {% for email in company.email_set.all %}
                                {% if email.company_id == company.id %}
                                <li>{{ email }}</li>
                                {% endif %}
                            {% endfor %}
                            </ul>
                        </dd>
                </dl>
                <div class="border-bottom text-right fs-_8">
                    created: {{ company.created_date|date:"d.m.Y" }} in {{ company.created_date|time:"H:i" }}
                        [<span class="text-danger">last changed: {{ company.updated_date|date:"d.m.Y" }}
                            in {{ company.updated_date|time:"H:i" }}</span>]
                </div>
                {% if company.project_set.all %}
                    <div class="d-flex justify-content-between align-items-center">
                        <small class="d-block mt-3 align-self-start">
                            {% if perms.someapp.add_project %}
                            <a href="{% url 'new-project' company.slug %}"> + add a new project</a>
                            {% endif %}
                        </small>
                        <h3 class="my-5 text-center">Projects</h3>
                        <div class="mt-3 align-self-start">
                            <form method="get">
                                <select name="sorting" id="sorting" class="d-block form-control mb-3"
                                        onchange="$(this).parent().submit();">
                                    <option value="none">All projects</option>
                                    <option value="left">New projects</option>
                                    <option value="in_progress">In progress projects</option>
                                    <option value="completed">Completed projects</option>
                                </select>
                            </form>
                        </div>
                        <script>
                            let path = '{{ request.get_full_path|cut:request.path }}'.slice(1,);
                                reqObj = getDict(path);
                        </script>
                    </div>
                    <div>
                        {% for project in page_obj %}
                            {% now 'Y-m-d' as today %}

                            {% if project.begin|date:"Y-m-d" > today %}
                            <div class="card border-secondary mb-3">
                                <div class="card-header text-right text-secondary">
                                    Will be started {{project.begin|date:"d.m.y"}}
                                </div>
                            {% elif project.end|date:"Y-m-d" < today %}
                            <div class="card border-success mb-3">
                                <div class="card-header text-right text-success">
                                    Completed
                                </div>
                            {% else %}
                            <div class="card border-info mb-3">
                                <div class="card-header text-right text-info">
                                    In Progress
                                </div>
                            {% endif %}

                                <div class="card-body text-secondary">
                                    <h5 class="card-title">
                                        <a href="{{ project.get_absolute_url }}">{{ project.title }}</a>
                                    </h5>
                                    <p class="card-text">{{ project.description|safe }}</p>
                                </div>
                                <h4 class="card-header">
                                    <span class="text-secondary font-italic">Price of project:</span>
                                    ${{ project.price }}
                                </h4>
                            </div>
                        {% endfor %}

                        <nav class="container mt-5">
                            <ul class="pagination">
                                {% include "pagination.html" %}
                            </ul>
                        </nav>
                    </div>
                {% else %}
                <div class="position-relative py-5 my-4">
                    <h3 class="text-secondary get-center">
                        There are no projects available
                        {% if perms.someapp.add_project %}
                        <small class="d-block text-center mt-3">
                            <a href="{% url 'new-project' company.slug %}"> + add a new project</a>
                        </small>
                        {% endif %}
                    </h3>
                </div>
                {% endif %}
            </div>
        </div>
    </main>

{% endblock %}

someapp/templates/someapp/company_confirm_delete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Delete {{ company.title }}
{% endblock %}

{% block menu_1 %}
    <li class="nav-item">
        <a class="nav-link text-primary" href="{% url 'companies' %}">Company List</a>
    </li>
    <li class="nav-item ml-5">
        <a class="nav-link text-primary" href="{% url 'projects' %}">All Projects</a>
    </li>
{% endblock %}

{% block menu_2 %}
    <li class="nav-item">
        <a class="nav-link text-primary" href="{% url 'cabinet' %}">Personal Room</a>
    </li>
{% endblock %}

{% block content %}

    <main class="container">
        <div class="row">

                    <div class="text-secondary get-center">
                        <h4 class="text-center">Are you sure you want to delete "{{ company.title }}"?</h4>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="I'm sure" class="shadow rounded font-weight-bold text-uppercase mt-5 py-2 w-50 btn btn-danger d-block mx-auto">
                        </form>
                    </div>
        </div>
    </main>

{% endblock %}

someapp/templates/someapp/company_update.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block addjs %}
<script src="{% static 'js/addcontacts.js' %}"></script>
{% endblock %}

{% block title %}
    Update {{ company.title }}
{% endblock %}

{% block content %}

    <noscript class="d-block text-center bg-warning text-light py-3">
        This page requires Javascript to work correctly.
    </noscript>
    <main class="container">
        <div class="row">
            <div class="col-9 mx-auto col-md-6 col-lg-6">
                <h1 class="my-5 text-center" id="update">Update {{ company.title }}</h1>
                <form action="" method="post" id="form_company">
                    {% csrf_token %}
                    {{ form.media }}
                    <p>{{ form|crispy }}</p>
                    {{ phone.management_form }}
                    <div id="phone_set" class="mt-3">
                        <div id="initial_phone">
                            {% for number in phone.forms %}
                                <ul class='phone-number'>
                                    {{ number.as_ul }}
                                </ul>
                            {% endfor %}
                        </div>
                        <div id="additional_phone"></div>

                        <a class="btn btn-link" id="add_phone" onclick="addPhone();"> + Add </a>

                        <div id="empty_phone" class="d-none">
                            <ul class='phone-number'>
                                {{ phone.empty_form.as_ul }}
                            </ul>
                        </div>
                        <span id="extra_phone" class="d-none">{{ phone.extra }}</span>
                    </div>
                    <hr>

                    {{ email.management_form }}
                    <div id="email_set" class="mt-3">
                        <div id="initial_email">
                            {% for mail in email.forms %}
                                <ul class='email'>
                                    {{ mail.as_ul }}
                                </ul>
                            {% endfor %}
                        </div>
                        <div id="additional_email"></div>

                        <a class="btn btn-link" id="add_email" onclick="addEmail();"> + Add </a>

                        <div id="empty_email" class="d-none">
                            <ul class='email'>
                                {{ email.empty_form.as_ul }}
                            </ul>
                        </div>
                        <span id="extra_email" class="d-none">{{ email.extra }}</span>
                    </div>

                    <button type="submit" class="btn btn-success d-block mx-auto mt-4 py-2 px-5">Update</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </main>

{% endblock %}

someapp/templates/someapp/new-company.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block addjs %}
<script src="{% static 'js/addcontacts.js' %}"></script>
{% endblock %}

{% block title %}
    Create New Company
{% endblock %}

{% block content %}

    <noscript class="d-block text-center bg-warning text-light py-3">
        This page requires Javascript to work correctly.
    </noscript>
    <main class="container">
        <div class="row">
            <div class="col-6 mx-auto col-md-6 col-lg-6">
                <h1 class="my-5 text-center" id="create">Create New Company</h1>
                <form action="" method="post" id="form_company">
                    {% csrf_token %}
                    <table>
                    {{ form.media }}
                    {{ form|crispy }}
                    </table>
                    <hr>
                    {{ phone.management_form }}
                    <div id="phone_set" class="mt-3">
                        <div id="initial_phone">
                            {% for number in phone.forms %}
                                <ul class='phone-number'>
                                    {{ number.as_ul }}
                                </ul>
                            {% endfor %}
                        </div>
                        <div id="additional_phone"></div>

                        <a class="btn btn-link" id="add_phone" onclick="addPhone();"> + Add </a>

                        <div id="empty_phone" class="d-none">
                            <ul class='phone-number'>
                                {{ phone.empty_form.as_ul }}
                            </ul>
                        </div>
                        <span id="extra_phone" class="d-none">{{ phone.extra }}</span>
                    </div>
                    <hr>

                    {{ email.management_form }}
                    <div id="email_set" class="mt-3">
                        <div id="initial_email">
                            {% for mail in email.forms %}
                                <ul class='email'>
                                    {{ mail.as_ul }}
                                </ul>
                            {% endfor %}
                        </div>
                        <div id="additional_email"></div>

                        <a class="btn btn-link" id="add_email" onclick="addEmail();"> + Add </a>

                        <div id="empty_email" class="d-none">
                            <ul class='email'>
                                {{ email.empty_form.as_ul }}
                            </ul>
                        </div>
                        <span id="extra_email" class="d-none">{{ email.extra }}</span>
                    </div>

                    <input type="submit" value="Submit" class="btn-success">
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </main>

{% endblock %}

someapp/templates/someapp/new-project.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}
    Create New Company
{% endblock %}

{% block content %}

    <noscript class="d-block text-center bg-warning text-light py-3">
        This page requires Javascript to work correctly.
    </noscript>
    <main class="container">
        <div class="row">
            {% if perms.someapp.add_project %}
            <div class="col-6 mx-auto col-md-6 col-lg-6">
                <h1 class="my-5 text-center">Create New Project</h1>
                <form action="" method="post" id="form_company">
                    {% csrf_token %}
                    <table>
                    {{ form.media }}
                    {{ form|crispy }}
                    </table>
                    <hr>

                    <input type="submit" value="Submit" class="btn-success">
                    <div class="clearfix"></div>
                </form>
            </div>
            {% endif %}
        </div>
    </main>

{% endblock %}