main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('someapp.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns = [
                      path('__debug__/', include('debug_toolbar.urls')),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from users import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('accounts/', include([
        path('personal-room/', include([
            path('', views.PersonView.as_view(), name='cabinet'),
            path('update/', views.PersonUpdate.as_view(), name='cabinet-update'),
            path('delete/', views.PersonDelete.as_view(), name='cabinet-delete'),
            path('change-password-set/', views.PersonPasswordChange.as_view(), name='change-password-set'),
        ])),
        path('password-reset/', include([
            path('', views.PersonPasswordReset.as_view(), name='password_reset'),
            path('done/', auth_views.PasswordResetDoneView.as_view(template_name='reset/password_reset_done.html'),
                 name='password_reset_done'),
            path('confirm/<uidb64>/<token>/',
                 auth_views.PasswordResetConfirmView.as_view(template_name='reset/password_reset_confirm.html'),
                 name='password_reset_confirm'),
            path('complete/',
                 auth_views.PasswordResetCompleteView.as_view(template_name='reset/password_reset_complete.html'),
                 name='password_reset_complete'),
        ])),
    ])),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

interactions/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse_lazy
from main import settings
from main.constants import APPEALS
from someapp.models import Project, Company


class Interaction(models.Model):
    """Model representing a interactions between company and manager"""
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    appeals = models.CharField(max_length=2, choices=APPEALS.choices, default=APPEALS.REQUEST)
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = RichTextField(config_name='comment_ckeditor')
    keyword = models.ManyToManyField('Keyword', related_name='keyword', blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_date',)
        verbose_name = 'interaction'
        verbose_name_plural = 'interactions'

    def __str__(self) -> str:
        """String for representing a interaction object."""
        return self.get_appeals()

    def get_appeals(self) -> str:
        """Method to get a value of appeals"""
        return f'{APPEALS(self.appeals).label}'


class Keyword(models.Model):
    """Model representing a keyword"""
    title = models.CharField(max_length=255, unique=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_date',)
        verbose_name = 'keyword'
        verbose_name_plural = 'keywords'

    def __str__(self) -> str:
        """String for representing a keyword object."""
        return f'{self.title}'


class Like(models.Model):
    """Model representing a Like"""
    who = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    action = models.ForeignKey(Interaction, on_delete=models.CASCADE)
    like = models.ForeignKey("Rating", on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_date',)
        verbose_name = 'like'
        verbose_name_plural = 'likes'

    def __str__(self) -> str:
        """String for representing the CommentLike object."""
        return f'{self.action} - {self.who}'


class Rating(models.Model):
    """Model representing a Rating"""
    value = models.SmallIntegerField(default=0)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-value',)
        verbose_name = 'rating'
        verbose_name_plural = 'rating'

    def __str__(self) -> str:
        """String for representing a Rating object."""
        return f'{self.value}'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator
from django.db import models
from main.utils import valid_username, update_to


class Person(AbstractUser):
    """Model representing a person"""
    username = models.CharField(
        max_length=150,
        unique=True,
        help_text="Required. 150 characters or fewer. Letters, and digits only.",
        validators=[valid_username],
        error_messages={
            'unique': "A user with that username already exists.",
        },
    )
    image = models.ImageField(upload_to=update_to,
                              validators=[FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg'])],
                              default='default.png')

    class Meta:
        ordering = ('username', '-date_joined',)
        verbose_name = 'Person'
        verbose_name_plural = 'Persons'

    def __str__(self) -> str:
        """String for representing a Person object."""
        return f'{self.username}'

    def save(self, *args, **kwargs) -> None:
        """Custom save new image method
        Args:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        try:
            this = Person.objects.get(id=self.id)
            if this.image != self.image:
                this.image.delete(save=False)
        except:
            pass
        super().save(*args, **kwargs)

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .models import Person


class PersonCreationForm(UserCreationForm):
    """Form for create a new person objects"""
    class Meta(UserCreationForm):
        model = Person
        fields = ('username', 'email')


class PersonChangeForm(UserChangeForm):
    """Form for change data person objects"""
    class Meta:
        model = Person
        fields = ('username', 'email')


class PersonUpdateForm(forms.ModelForm):
    """Form for update person objects"""
    class Meta:
        model = Person
        fields = ('username', 'first_name', 'last_name', 'email', 'image',)

users/views.py
from typing import Any, Union, Optional
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, PasswordResetForm
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.auth.views import PasswordChangeView, PasswordResetView
from django.core.mail import send_mail
from django.http import HttpResponseRedirect, HttpResponsePermanentRedirect, HttpResponse, HttpRequest
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import View
from main import settings
from users.forms import PersonUpdateForm, PersonCreationForm
from users.models import Person
from django.views.generic import ListView, UpdateView, DeleteView, CreateView


class SignUp(CreateView):
    """Controller for registration a custom user"""
    form_class = PersonCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'
    email_subject = 'Welcome!'
    email_content_to_send = 'users/signup_email.html'
    messages_type = messages.SUCCESS

    def form_valid(self, form: PersonCreationForm) -> HttpResponseRedirect:
        """Checking the validity of the form data"""
        if self.request.POST:
            form = PersonCreationForm(self.request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                signup_user = Person.objects.get(username=username)
                user_group = Group.objects.get(name='Users')
                user_group.user_set.add(signup_user)
                text_mail = render_to_string(
                    self.email_content_to_send,
                    {
                        'user_name': username,
                        'link': f"{self.request.scheme}://{self.request.get_host()}{self.success_url}",
                    }
                )
                send_mail(
                    self.email_subject,
                    None,
                    settings.EMAIL_HOST_USER,
                    [form.cleaned_data.get('email')],
                    fail_silently=False,
                    html_message=text_mail,
                )
                messages.add_message(
                    self.request,
                    self.messages_type,
                    f'User {username} registered successfully',
                )
            else:
                return super().form_invalid(form)
        else:
            form = PersonCreationForm()
        return super().form_valid(form)


class LoginView(View):
    """Controller for log in"""
    template_name = 'users/login.html'
    messages_type_agree = messages.SUCCESS
    messages_type_disagree = messages.ERROR

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        """Method for getting the form data"""
        form = AuthenticationForm(data=request.POST)
        return render(request, self.template_name, {'form': form})

    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> Union[HttpResponsePermanentRedirect,
                                                                             HttpResponseRedirect, HttpResponse]:
        """Method for processing the form data"""
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.add_message(
                    self.request,
                    self.messages_type_agree,
                    f'Welcome, {username}!',
                )
                return redirect('companies')
            else:
                messages.add_message(
                    self.request,
                    self.messages_type_disagree,
                    f'Unfortunately, the user with username {username} is not registered on this website',
                )
                return redirect('login')

        return render(request, self.template_name, {'form': form})


class LogoutView(View):
    """Controller for log out"""
    def get(self, request: HttpRequest) -> Union[HttpResponsePermanentRedirect, HttpResponseRedirect]:
        """Method for getting the form data"""
        logout(request)
        return redirect(settings.LOGIN_URL)


class PersonView(LoginRequiredMixin, ListView):
    """Controller for viewing personal information for active person"""
    model = Person
    template_name = "users/cabinet.html"
    context_object_name = "selfroom"

    def get_queryset(self) -> Any:
        """Method for getting a queryset"""
        queryset = self.request.user
        return queryset


class PersonUpdate(PermissionRequiredMixin, UpdateView):
    """Controller for update a personal data"""
    model = Person
    form_class = PersonUpdateForm
    permission_required = 'users.change_person'
    template_name_suffix = '_update'
    success_url = reverse_lazy('cabinet')
    messages_type = messages.SUCCESS
    email_content_to_send = 'users/cabinet_update_email.html'

    def get_object(self, queryset: Optional[Any] = None) -> Any:
        """Method for getting a object"""
        queryset = self.request.user
        return queryset

    def form_valid(self, form: PersonUpdateForm) -> HttpResponseRedirect:
        """Checking the validity of the form data"""
        changed_poles = dict()
        for items in Person.objects.filter(username=self.request.user).values():
            for key, val in items.items():
                if val != form.cleaned_data.get(key) and form.cleaned_data.get(key) is not None:
                    changed_poles[key] = form.cleaned_data.get(key)

        text_mail = render_to_string(
            self.email_content_to_send,
            {
                'user_name': Person.objects.get(username=self.request.user),
                'updated': changed_poles,
                'link': f"{self.request.scheme}://{self.request.get_host()}{self.success_url}",
            }
        )
        send_mail(
            'Data Update',
            None,
            settings.EMAIL_HOST_USER,
            [form.cleaned_data.get('email')],
            fail_silently=False,
            html_message=text_mail,
        )
        messages.add_message(
            self.request,
            self.messages_type,
            f'Data has been changed successfully',
        )
        return super().form_valid(form)


class PersonDelete(PermissionRequiredMixin, DeleteView):
    """Controller for delete person"""
    model = Person
    permission_required = 'users.delete_person'
    success_url = reverse_lazy('login')

    def get_object(self, queryset: Optional[Any] = None) -> Any:
        """Method for getting a object"""
        queryset = self.request.user
        return queryset


class PersonPasswordChange(LoginRequiredMixin, PasswordChangeView):
    """Controller for update a user password"""
    template_name = 'users/person_password_change.html'
    success_url = reverse_lazy('cabinet')
    messages_type = messages.SUCCESS

    def form_valid(self, form: PasswordChangeForm) -> HttpResponseRedirect:
        """Checking the validity of the form data"""
        send_mail(
            'Changed Password',
            'Your password has been changed successfully',
            settings.EMAIL_HOST_USER,
            [self.request.user.email],
            fail_silently=False,
        )
        messages.add_message(
            self.request,
            self.messages_type,
            f'Password has been changed successfully',
        )
        return super().form_valid(form)


class PersonPasswordReset(PasswordResetView):
    """Controller for reset a user password"""
    template_name = 'reset/password_reset_form.html'
    email_template_name = 'reset/password_reset_email.html'
    messages_type = messages.SUCCESS

    def form_valid(self, form: PasswordResetForm) -> HttpResponseRedirect:
        """Checking the validity of the form data"""
        messages.add_message(
            self.request,
            self.messages_type,
            f"https://{form.cleaned_data.get('email').split('@')[-1]}",
        )
        return super().form_valid(form)

users/templates/users/cabinet.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Personal Room
{% endblock %}

{% block content %}

{% if messages %}
    {% include "message.html" %}
{% endif %}

<main class="container">
    <div class="row">
        <div class="col-3 col-md-3 col-lg-3 ">
            <img class="user-img" src="{{ selfroom.image.url }}"
                 alt="{{ selfroom.last_name }} {{ selfroom.first_name }}">
        </div>
        <div class="col-6 col-md-6 col-lg-6">
            <h1 class="my-5 text-center">Personal Room
                <a class="ml-5" href="{% url 'cabinet-update' %}">
                    <span class="material-icons">edit</span>
                </a>
                <a class="ml-5" href="{% url 'cabinet-delete' %}">
                    <span class="material-icons">delete</span>
                </a>
            </h1>
            <dl class="row ml-5">
                <dt class="col-sm-5 mb-3">Username:</dt>
                    <dd class="col-sm-7">{{ selfroom.username }}</dd>
                <dt class="col-sm-5 mb-3">First Name:</dt>
                    <dd class="col-sm-7">{{ selfroom.first_name }}</dd>
                <dt class="col-sm-5 mb-3">Last Name:</dt>
                    <dd class="col-sm-7">{{ selfroom.last_name }}</dd>
                <dt class="col-sm-5 mb-3">E-mail:</dt>
                    <dd class="col-sm-7">{{ selfroom.email }}</dd>
                <dt class="col-sm-5 mb-3">Group:</dt>
                    {% if selfroom.groups.all.0 is None %}
                    <dd class="col-sm-7">Administrators</dd>
                    {% else %}
                    <dd class="col-sm-7">{{ selfroom.groups.all.0.name }}</dd>
                    {% endif %}
                <hr>
                <dt class="col-sm-5 mb-3">Access Grant Date:</dt>
                    <dd class="col-sm-7">{{ selfroom.date_joined }}</dd>
                <dt class="col-sm-5 mb-3">Last Visit:</dt>
                    <dd class="col-sm-7">{{ selfroom.last_login }}</dd>
                <dt class="col-sm-5 mb-3"></dt>
                    <dd class="col-sm-7"><a href="{% url 'change-password-set' %}">Change Password</a></dd>
            </dl>
        </div>
    </div>
    <hr>

    <div class="row">
        <div class="col-12 col-md-5 col-lg-5">
            <p class="text-secondary text-center">Projects</p>
            <ul>
                {% for project in selfroom.responsible.all %}
                <li>
                    <a href="{{ project.get_absolute_url }}" class="mr-3">{{ project.title }}</a>
                     -
                    <span class="ml-3">[status:
                        <span class="{{ project.days_to.1 }}">{{ project.days_to.0 }}</span>]
                    </span>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-12 col-md-7 col-lg-7">
            <p class="text-secondary text-center">Interactions</p>
            <ul type="circle">
                {% for action in selfroom.interaction_set.all %}
                <li>
                    <span class="d-block">
                        {% with project=action.project %}
                        <a href="
                        {% url 'interaction-details' project.company.slug project.slug action.pk %}">
                        {% endwith %}
                            {{ action.description|safe|truncatechars:70 }}
                        </a>
                    </span>
                    <small class="d-block text-muted">[{{ action.get_appeals }} - Project:
                        {{ action.project.title|lower }}]</small>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</main>

{% endblock %}

users/templates/users/cabinet_update_email.html
{% load templatetags %}

<h3>Dear {{ user_name }}!</h3>

<p>Your personal data has been changed. The following fields have been modified:</p>

{% for key, val in updated.items %}
    <p><strong>{{ key|replace:"_| "|title }}:</strong> {{ val }}</p>
{% endfor %}

<br>
<p>Go to <a href="{{ link }}">Log In</a></p>

users/templates/users/login.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block addjs %}
<script src="{% static 'js/showed.js' %}"></script>
{% endblock %}

{% block title %}
    Login
{% endblock %}

{% block content %}

    {% if messages %}
        {% include "message.html" %}
    {% endif %}

    {% if user.is_authenticated %}
        <meta http-equiv="REFRESH" content="0;url={% url 'companies' %}">
    {% else %}
        <main class="container"><br>
            <h1 class="text-center mt-5 text-secondary">Login</h1>
            <div class="row">
                <div class="col-12 col-sm-12 col-lg-6 bg-light mx-auto mt-5"><br>
                    <form method="post" class="col-11">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="d-flex justify-content-between mb-2">
                            <a href="{% url 'signup' %}" class="btn btn-outline-primary mt-4 py-2 px-5">Sign Up</a>
                            <button type="submit" class="btn btn-primary mt-4 py-2 w-50">Log In</button>
                        </div>
                        <div>
                            <a href="{% url 'password_reset' %}" class="btn-link float-right mr-5">
                                I Forgot a Password
                            </a>
                            <div class="clearfix"></div>
                        </div>
                    </form>
                    <br>
                </div>
            </div>
            <br>
        </main>
        <br>
    {% endif %}

{% endblock %}

users/templates/users/person_confirm_delete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Delete {{ user.username }}
{% endblock %}

{% block content %}

    <main class="container">
        <div class="row">

                    <div class="text-secondary get-center">
                        <h4 class="text-center">Are you sure you want to delete account "{{ user.username }}"?</h4>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="I'm sure"
                                   class="shadow rounded font-weight-bold text-uppercase mt-5 py-2 w-50
                                    btn btn-danger d-block mx-auto">
                        </form>
                    </div>
        </div>
    </main>

{% endblock %}

users/templates/users/person_password_change.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block addjs %}
<script src="{% static 'js/showed.js' %}"></script>
{% endblock %}

{% block title %}
    Change Password
{% endblock %}

{% block content %}

<main class="container">
    <h2 class="text-center my-5">Change Password</h2>
    <div class="row">
        <div class="col-12 col-sm-12 col-lg-6 bg-light mx-auto mt-5">

            {% if form.user.username == user.username %}
                <form method="post">
                    {% csrf_token %}
                    <div>
                        <small class="font-italic float-right my-3 text-underline">
                            Please enter your new password twice
                        </small>
                        <div class="clearfix"></div>
                    </div>
                    <div class="col-11">
                        {{ form|crispy }}
                    </div>
                    <div class="my-4 text-center">
                        <input type="submit" class="btn btn-primary w-50" value="Change">
                        <div class="clearfix"></div>
                    </div>
                </form>
            {% else %}
                <script>window.history.back();</script>
            {% endif %}

        </div>
    </div>

</main>

{% endblock %}

users/templates/users/person_update.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}
    Update {{ user.username }}
{% endblock %}

{% block content %}

    <noscript class="d-block text-center bg-warning text-light py-3">
        This page requires Javascript to work correctly.
    </noscript>
    <main class="container">
        <div class="row">
            <div class="col-9 mx-auto col-md-6 col-lg-6">
                <h1 class="my-5 text-center" id="update">{{ user.username }}</h1>
                <form action="" method="post" id="form_company" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>{{ form|crispy }}</p>
                    <button type="submit" class="btn btn-success d-block mx-auto mt-4 py-2 px-5">Update</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </main>

{% endblock %}

users/templates/users/signup.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block addjs %}
<script src="{% static 'js/showed.js' %}"></script>
{% endblock %}

{% block title %}
    Sign Up
{% endblock %}

{% block content %}

        <main class="container"><br>
            <div class="row">
                <div class="col-12 col-sm-12 col-lg-7 bg-light mx-auto mt-5"><br>

                    <div>
                        {% if not form.is_valid %}
                        <div>
                            <br>
                            <h1 class="text-center text-secondary">Create a new account</h1>
                            <br>
                            <div class="col-9 col-sm-12 col-md-10 col-lg-10 mx-auto bg-light">
                                <br>
                                <p class="text-secondary">
                                    Please input the following information to create a new account
                                </p>
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form | crispy }}
                                    <button type="submit" name="submit"
                                            class="btn btn-secondary my-5 w-50 mx-auto d-block">SignUp</button>
                                </form>
                            </div>
                        </div>
                        {% else %}
                        <div class="mx-auto">
                            <br>
                            <h1 class="text-center text-success">Your account has been successfully created</h1>
                            <br>
                            <div>
                                <p class="text-secondary">Your account has been created and ready to use!
                                    <a class="btn btn-link" href="{% url 'login' %}">LogIn, Please</a>
                                </p>
                                <br>
                            </div>
                        </div>
                        {% endif %}
                    </div>

                    <br>
                </div>
            </div>
            <br>
        </main>
        <br>

{% endblock %}

users/templates/users/signup_email.html
<h3>Dear, {{ user_name }}!</h3>
<p>We are glad to welcome you on our website.</p>

<br>
<a href="{{ link }}">Go to Log in</a>
<br><br>

<small><ins>If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.</ins></small>